# Generated by Django 5.2.1 on 2025-06-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('name', models.CharField(max_length=50)),
                ('sub_text', models.TextField(max_length=500)),
            ],
        ),
    ]
